title: My Data Science Learning Journey
author: GitHub User
email: fahmina.parvej@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my blog. I am coming from a non-technical background and working towards achieving my career objectives of becoming a Data Scientist... Will I be succssful? Keep in touch to find out... 

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Fahmina02 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
